name: PUSH

on:
  push:
    tags:
      - "*"

jobs:
  github-to-svn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install composer packages
      run: composer install --no-dev
    - name: push to svn
      run: bash github-to-svn.sh
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
