name: SVN

on:
  push:
    tags:
      - "*"

jobs:
  github-to-svn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install svn
      run: sudo apt install -y subversion
    - name: push to svn
      run: bash github-to-svn.sh
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
